# Generated by Django 4.1.3 on 2023-05-25 18:47

import django.core.validators
from django.db import migrations, models
import petstagram.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0006_alter_pet_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[petstagram.validators.size_validator])),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, max_length=30)),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('tagget_pets', models.ManyToManyField(blank=True, to='pets.pet')),
            ],
        ),
    ]
